-- AC24 — correct the mislabeled date field on billing.document. The column
-- `reference_date` was always the inert, user-entered, defaults-to-today field
-- (captioned "Reference Date" in the UI, now corrected to "Entry Date"); rename
-- it so the column name matches its real behavior and corrected caption.
-- `event_at` — the document's true business-event date that drives period
-- validation + GL-journal grouping (now captioned "Reference Date") — is left
-- entirely untouched.
--
-- Hand-authored, not drizzle-kit generated: RENAME COLUMN is data-preserving
-- (it keeps every already-posted document's value, plus NOT NULL and
-- DEFAULT now()), whereas a naive DROP + ADD would silently discard the data.
ALTER TABLE billing.document RENAME COLUMN reference_date TO entry_date;
