import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
  buildGeneratedSql,
  splitTopLevelStatements,
} from "@/db/pgledger/transform";

// No DATABASE_URL needed — this is a pure text-transform check (ac01-spec
// §3.7 "Transform unit test (no DB)"). Runs in the default (non-integration)
// Vitest project.

const PGLEDGER_DIR = join(process.cwd(), "db", "pgledger");
const pgledgerSql = readFileSync(join(PGLEDGER_DIR, "pgledger.sql"), "utf8");
const upstreamCommit = readFileSync(
  join(PGLEDGER_DIR, "UPSTREAM_COMMIT"),
  "utf8",
).trim();
const committedGenerated = readFileSync(
  join(PGLEDGER_DIR, "billing-pgledger.generated.sql"),
  "utf8",
);

describe("pgledger transform", () => {
  it("is in sync: re-running on the vendored inputs reproduces the committed generated file byte-for-byte", () => {
    const rebuilt = buildGeneratedSql(pgledgerSql, upstreamCommit);
    expect(rebuilt).toBe(committedGenerated);
  });

  it("is idempotent: running it twice on the same inputs yields identical output", () => {
    const first = buildGeneratedSql(pgledgerSql, upstreamCommit);
    const second = buildGeneratedSql(pgledgerSql, upstreamCommit);
    expect(second).toBe(first);
  });

  it("carries the generated banner naming the pinned upstream commit", () => {
    expect(committedGenerated).toContain(
      `-- GENERATED by db/pgledger/transform.ts from pgledger.sql @ ${upstreamCommit} — DO NOT EDIT`,
    );
  });

  it("qualifies namespaces without changing function-body logic", () => {
    // Every CREATE FUNCTION body in the generated output equals the
    // upstream body with only `billing.` qualification and the injected
    // `SET search_path` differing (§2.2 / §3.7) — strip both, then compare
    // token-for-token against the corresponding upstream statement.
    const upstreamStatements = splitTopLevelStatements(pgledgerSql);
    const generatedBody = committedGenerated.replace(
      /^-- GENERATED.*\n-- Regenerate.*\n\n/,
      "",
    );
    // Reverse transform.ts's own join exactly (not re-run through the
    // dollar-quote splitter) — re-splitting the joined text on `;` would
    // glue each `--> statement-breakpoint` marker onto the front of the
    // following statement instead of reproducing the original array.
    const generatedStatements = generatedBody.split(
      "\n--> statement-breakpoint\n\n",
    );

    expect(generatedStatements.length).toBe(upstreamStatements.length);

    const functionStatements = generatedStatements
      .map((stmt, i) => ({ stmt, upstream: upstreamStatements[i] }))
      .filter(({ stmt }) =>
        /^(--.*\n)*CREATE (OR REPLACE )?FUNCTION\b/.test(stmt),
      );

    // Sanity: the file has exactly 9 functions (transform.ts's own
    // EXPECTED_COUNTS.functions) — fail loudly here too if that drifts,
    // rather than silently comparing zero function bodies.
    expect(functionStatements.length).toBe(9);

    for (const { stmt, upstream } of functionStatements) {
      expect(upstream).toBeDefined();
      const stripped = stmt
        .replaceAll("billing.", "")
        .replace(/ SET search_path = billing, pg_catalog/g, "");
      // Case-insensitive: qualifying `TRANSFER_REQUEST` → `billing.transfer_request`
      // lowercases that one identifier (Postgres folds unquoted identifiers
      // to lowercase regardless, so this is not a behaviour change) — the
      // comparison cares about token/logic equivalence, not source casing.
      expect(stripped.trim().toLowerCase()).toBe(
        upstream!.trim().toLowerCase(),
      );
    }
  });

  it("leaves no unqualified pgledger_* reference in the generated output", () => {
    const codeOnly = committedGenerated
      .split("\n")
      .map((line) => {
        const idx = line.indexOf("--");
        return idx === -1 ? line : line.slice(0, idx);
      })
      .join("\n");
    expect(codeOnly).not.toMatch(/(?<!billing\.)\bpgledger_\w+/i);
  });

  it("leaves no unqualified uuid_to_ulid or TRANSFER_REQUEST reference in the generated output", () => {
    const codeOnly = committedGenerated
      .split("\n")
      .map((line) => {
        const idx = line.indexOf("--");
        return idx === -1 ? line : line.slice(0, idx);
      })
      .join("\n");
    expect(codeOnly).not.toMatch(/(?<!billing\.)\buuid_to_ulid\b/i);
    expect(codeOnly).not.toMatch(/\bTRANSFER_REQUEST\b/);
  });

  it("preserves the one upstream comment that mentions a pgledger_ function name verbatim", () => {
    // §2.2: comment prose is left untouched, even when it happens to
    // mention a pgledger_ identifier by name.
    expect(committedGenerated).toContain(
      "-- Simply call pgledger_create_transfers with a single transfer",
    );
  });
});
