export * from "@/db/schema/identity";
export * from "@/db/schema/audit";
export * from "@/db/schema/roles";
export * from "@/db/schema/permissions";
export * from "@/db/schema/role-permission-assign";
export * from "@/db/schema/role-assign";
export * from "@/db/schema/system-config";
export * from "@/db/schema/product";
export * from "@/db/schema/customer";
